# Generated by Django 4.2.2 on 2023-06-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_mainservice_time_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainservice',
            name='time_off',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='time_on',
            field=models.DateField(),
        ),
    ]
