# Generated by Django 4.2.1 on 2023-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0004_alter_mainservice_time_off_alter_mainservice_time_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("rating", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
