# Generated by Django 4.1.7 on 2023-06-21 07:49

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_alter_mainservice_time_off_alter_mainservice_time_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_time',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
