# Generated by Django 4.2 on 2023-06-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0007_rename_room_number_guest_room'),
        ('service_app', '0004_alter_mainservice_time_off_alter_mainservice_time_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.FloatField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_app.guest')),
                ('main_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.mainservice')),
            ],
        ),
    ]
