# Generated by Django 4.2 on 2023-06-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='guest',
        ),
    ]
