# Generated by Django 4.1.7 on 2023-06-21 07:50

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_review_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_time',
            field=models.DateTimeField(timezone.now()),
        ),
    ]
