# Generated by Django 4.1.7 on 2023-06-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_review'),
        ('service_app', '0006_alter_mainservice_time_off_alter_mainservice_time_on'),
    ]

    operations = [
    ]
