# Generated by Django 4.2 on 2023-06-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_remove_review_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
