# Generated by Django 4.1.7 on 2023-06-19 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_merge_20230619_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainservice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='time_off',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 13, 59, 41, 9638, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='time_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 13, 59, 41, 9638, tzinfo=datetime.timezone.utc)),
        ),
    ]
