# Generated by Django 4.1.7 on 2023-06-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_remove_review_date_time_subservicerequest_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservicerequest',
            name='is_delivered',
            field=models.CharField(choices=[('new_request', 'new request'), ('in_progress', 'in_progress'), ('delivered', 'delivered'), ('refuesed', 'refuesed')], default='new_request', max_length=50),
        ),
    ]
