# Generated by Django 4.1.7 on 2023-06-19 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0019_alter_mainservice_time_off_alter_mainservice_time_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_cart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sub_service',
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='time_off',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 20, 15, 22, 516994, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='time_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 20, 15, 22, 516994, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='OrderCart',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
