# Generated by Django 4.2 on 2023-06-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_delete_review'),
        ('service_app', '0027_alter_mainservice_time_off_alter_mainservice_time_on'),
    ]

    operations = [
    ]
