# Generated by Django 4.2.1 on 2023-06-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest_app", "0002_alter_guest_phone_number_alter_guest_room_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="guest", name="user",),
    ]
