# Generated by Django 4.1.7 on 2023-06-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0004_rename_number_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest_app.room'),
            preserve_default=False,
        ),
    ]
