# Generated by Django 4.1.7 on 2023-06-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0008_guest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
