# Generated by Django 4.1.7 on 2023-06-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0010_guest_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
