# Generated by Django 4.1.7 on 2023-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0012_guest_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='all',
            field=models.BooleanField(default=True),
        ),
    ]
