# Generated by Django 4.1.7 on 2023-06-19 21:57
from django.utils import timezone

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0013_guest_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='all',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user_permissions',
        ),
    ]
